add eslint
OG-Jons/umessage pull request #24
Opened 2021-06-04 14:55 UTC by N1ck100

2021-06-07 09:45 UTC, Sl1van commented
Everything seems fine except the package-lock.json got committed.

2021-06-08 08:52 UTC, OG-Jons requested changes
Remove package-lock.json / add it to .gitignore

2021-06-08 08:56 UTC, OG-Jons commented on src/App.jsx
> +import React from 'react';
React import is not needed

2021-06-08 08:58 UTC, Nikzz3 commented on src/App.jsx
> +import React from 'react';
Without React import eslint throws error

2021-06-08 09:04 UTC, OG-Jons commented on src/App.jsx
> +import React from 'react';
Then eslint has too old formatting, react isn't needed anymore

2021-06-08 09:05 UTC, OG-Jons commented on src/App.jsx
> +import React from 'react';
https://stackoverflow.com/questions/44141010/do-i-need-to-import-react-for-stateless-functional-components
It's explained in detail here

2021-06-08 09:26 UTC, OG-Jons commented on .gitignore
> +package-lock.json
newline needed at the end of file

2021-06-08 09:26 UTC, OG-Jons commented on src/components/Example/Example.component.jsx
>  }
newline here too

2021-06-08 09:34 UTC, OG-Jons approved these changes
still against eslint, but eh

2021-06-09 11:22 UTC, Sl1van commented
👍

2021-06-09 11:24 UTC, Sl1van approved these changes
👍
everything seems fine

2021-06-09 11:25 UTC, merged